---
fixtures:
  forge_modules:
    epel:
      repo: "stahnma/epel"
      ref: "1.3.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "4.2.1"
    stdlib: "puppetlabs/stdlib"
    file_concat:
      repo: "electrical/file_concat"
      ref: "1.0.1"
  symlinks:
    awscli: "#{source_dir}"
